### PR TITLE
Remove Smalltalk globals references. 

### PR DESCRIPTION
**Pull request by Alisu**
Create an environment instance variable initialized at Smalltalk globals. Add a setter.

Change all Smalltalk globals to environment.

### CODE REVIEW

**Comment by tinchodias** [comment]
Hello. Changes look good (but I didn't load them).

**Comment by theseion** [comment]
Hi @Alisu

Sorry for the looooooong wait. If you're still around, can you comment on the reason for you PR? It's a nice change but it seems very specific to me. Was there some discussion about globals w.r.t. to Pharo that started this?

**Comment by theseion** [comment]
@estebanlm @tesonep @guillep do you know anything about this PR?

**Comment by Alisu** [comment]
Hello, I did not see your first message.
Yes, the idea was to clean references to globals and may be in a distant goal to have some 'modules' but I shifted from this for now and we are far from it.

**Comment by estebanlm** [comment]
I would close this for now :)

**Comment by theseion** [comment]
Ok, thanks. Just so you know, I've started using a separate environment for the tests because they do lots of class and global manipulations (which pretty much makes this PR obsolete anyway). I figured, it would be simpler to just discard changes than to carefully clean up everything that changed. In addition, this allows me to effectively test the environment handling of Fuel, which has long been built in and I did discover quite a few cases where it didn't work as expected :).

My experience with environments has been mixed so far. The idea of `AbstractEnvironmentTest` is great and in many places the use of a separate environment really works (e.g. class builder!). I did have to come up with two things myself though:
- a proxy for `Smalltalk globals`, that is used as the test environment, caching all the changes in an overlay. This can be simply discarded at the end of the test (happens implicitly) and the globals will remain untouched
- a custom implementation of `ClassFactoryForTestCase` that operates on a configurable environment and passes that environment to the class builder

There are still issues with some global lookups, especially w.r.t. `SystemOrganization` (e.g. when deleting behaviors), which would be nice to get fixed.

So, if you start working on environments again, maybe check out what I did for Fuel and feel free to integrate it.

**Pull request closed without merging**
